feat: implement Detail blog page
TITO-TRAINING/REACT pull request #12
Opened 2022-11-10 14:12 UTC by milo219

2022-11-10 14:44 UTC, demons1502 commented on src/components/DetailBlog/index.tsx
> +          {/* <include src="components/like-button.html"></include> */}
remove

2022-11-10 14:45 UTC, demons1502 commented on src/components/SocialShare/index.tsx
> +        <a title="Twitter" href="/">
define a constant and map it

2022-11-10 14:47 UTC, demons1502 commented on src/components/DetailBlog/index.tsx
> +  numberComment: string;
type of `numberComment` is string ?

2022-11-10 14:48 UTC, demons1502 commented on src/components/DetailBlog/index.tsx
> +            alt=""
Add alt

2022-11-10 14:49 UTC, demons1502 commented on src/components/DetailBlog/index.tsx
> +              <li>
define constant and map its

2022-11-10 14:49 UTC, demons1502 commented on src/components/DetailComment/index.tsx
> +          alt=""
Same

2022-11-11 12:07 UTC, baonguyen26 commented on src/App.tsx
> +import BlogPage from './pages/BlogPage';
Check order import

2022-11-11 12:27 UTC, baonguyen26 requested changes

2022-11-11 12:27 UTC, baonguyen26 commented on src/components/DetailBlog/index.tsx
> +  imgDetailBlog: string;
`image` instead

2022-11-11 12:27 UTC, baonguyen26 commented on src/components/DetailBlog/index.tsx
> +  tittleDetailBlog: string;
`title` instead

2022-11-11 12:27 UTC, baonguyen26 commented on src/components/DetailBlog/index.tsx
> +  content2: string;
second?

2022-11-11 12:27 UTC, baonguyen26 commented on src/components/DetailComment/index.tsx
> +  imgAvtComment: string;
naming?

2022-11-11 12:27 UTC, baonguyen26 commented on src/components/LikeButton/index.tsx
> +import { AiTwotoneLike } from 'react-icons/ai';
Do you have another way to handle it?

2022-11-11 12:27 UTC, baonguyen26 commented on src/components/LikeButton/index.tsx
> +  const [like, setLike] = useState(0);
type of state? 
`const [like, setLike] = useState<number>(0);`

2022-11-11 12:27 UTC, baonguyen26 commented on src/components/LikeButton/index.tsx
> +  const [isLike, setIsLike] = useState(false);
same here

2022-11-11 12:27 UTC, baonguyen26 commented on src/components/LikeButton/index.tsx
> +    setIsLike(!isLike);
`setIsLike((like) => !like);`

2022-11-11 12:27 UTC, baonguyen26 commented on src/components/LikeButton/index.tsx
> +export default function App() {
???

2022-11-11 12:27 UTC, baonguyen26 commented on src/components/LikeButton/index.tsx
> +      className={`like-button ${isLike ? 'liked' : ''}`}
define constant
eg: 
`const likeButtonClassName = `like-button ${isLike ? 'liked' : ''}``

2022-11-12 07:31 UTC, baonguyen26 commented on src/components/DetailBlog/index.tsx
> +  SecondContent: string;
lowercase

2022-11-12 07:32 UTC, baonguyen26 commented on src/components/LikeButton/index.tsx
> +  const likeButtonClassName = `like-button ${isLike ? 'liked' : ''}`;
`isLike && 'liked'`

2022-11-12 07:34 UTC, baonguyen26 approved these changes

2022-11-12 07:38 UTC, merged